name: GitHub Issues to Discord Integration

on:
  issues:
    types:
      - opened
      - closed
      - reopened
      - deleted

  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  trigger-periodic-issues-updates:
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
    uses: scondo-prof/theToolKit/.github/workflows/github-issues-discord-integration.yml@5-gh-periodic-issue-updates
    secrets: inherit
    with:
      trigger-periodic-issues-updates: true

  trigger-log-issue-details:
    if: github.event_name == 'issues'
    uses: scondo-prof/theToolKit/.github/workflows/github-issues-discord-integration.yml@5-gh-periodic-issue-updates
    secrets: inherit
    with:
      trigger-log-issue-details: true
