name: GitHub Issues to Discord Integration

on:
  issues:
    types:
      - opened
      - closed
      - reopened
      - deleted

  schedule:
    - cron: "0 20 * * *"

jobs:
  periodic-updates:
    name: Periodic Updates Invoke
    if: github.event_name == 'schedule'
    uses: scondo-prof/theToolKit/.github/workflows/github-issues-discord-periodic-updates.yml@5-gh-periodic-issue-updates
    secrets: inherit
  notify-discord:
    name: Notify Discord about Issue Events
    if: github.event_name == 'issues'
    uses: scondo-prof/theToolKit/.github/workflows/github-issues-discord-integration.yml@main
    secrets: inherit
