name: GitHub Issues to Discord Integration

on:
  issues:
    types:
      - opened
      - closed
      - reopened
      - deleted

  issue_comment:
    types:
      - created

  workflow_dispatch:

jobs:
  trigger-periodic-issues-updates:
    if: github.event_name == 'workflow_dispatch'
    uses: scondo-prof/theToolKit/.github/workflows/github-issues-discord-integration.yml@main
    secrets: inherit
    with:
      trigger-periodic-issues-updates: true

  trigger-log-issue-details:
    if: github.event_name == 'issues' || github.event_name == 'issue_comment'
    uses: scondo-prof/theToolKit/.github/workflows/github-issues-discord-integration.yml@main
    secrets: inherit
    with:
      trigger-log-issue-details: true
